import { test, expect } from '@playwright/test';

test('compact top navigation and resizable overlay preserve canvas bounds', async ({ page }) => {
  await page.goto('/workbench');
  await expect(page.locator('.react-flow__node').first()).toBeVisible();
  const navigation = await page.locator('.top-navigation').boundingBox();
  expect(navigation!.height).toBeLessThanOrEqual(46);
  await expect(page.locator('.sidebar')).toHaveCount(0);
  const canvas = page.locator('.react-flow');
  const original = await canvas.boundingBox();
  expect(original!.width).toBe(1440);
  const panel = page.getByRole('region', { name: '浮动对话窗口' });
  const before = await panel.boundingBox();
  const handle = page.getByRole('button', { name: '调整对话窗口大小' });
  const grip = await handle.boundingBox();
  await page.mouse.move(grip!.x + 10, grip!.y + 10);
  await page.mouse.down();
  await page.mouse.move(grip!.x - 90, grip!.y + 70, { steps: 8 });
  await page.mouse.up();
  const after = await panel.boundingBox();
  expect(after!.width).toBeCloseTo(before!.width + 100, 0);
  expect(after!.height).toBeCloseTo(before!.height + 60, 0);
  expect(await canvas.boundingBox()).toEqual(original);
  await handle.focus();
  await page.keyboard.press('ArrowRight');
  expect((await panel.boundingBox())!.width).toBe(after!.width - 20);
  await page.screenshot({ path: 'artifacts/demo2-desktop.png' });
  await page.getByRole('button', { name: '关闭浮动对话' }).click();
  await expect(panel).toHaveCount(0);
  expect(await canvas.boundingBox()).toEqual(original);
  await page.getByRole('button', { name: '展开对话' }).click();
  await expect(panel).toBeVisible();
  await page.setViewportSize({ width: 390, height: 700 });
  await expect.poll(async () => (await panel.boundingBox())!.width).toBeLessThanOrEqual(366);
  const mobile = await panel.boundingBox();
  expect(mobile!.x).toBeGreaterThanOrEqual(0);
  expect(mobile!.y + mobile!.height).toBeLessThanOrEqual(700);
  await page.screenshot({ path: 'artifacts/demo2-mobile.png' });
});
