'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Sparkles, ArrowUp, Plus, X, CornerDownLeft, ArrowUpRight } from 'lucide-react';
import { useDemo } from '@/features/growth/provider';
export function ConversationPanel() {
  const { growth, selectedId, select, messages, proposals, accept, send, previewProposal, spaceId } = useDemo(); const router=useRouter();
  const [input,setInput]=useState(''); const [showContexts,setShowContexts]=useState(false); const bottom=useRef<HTMLDivElement>(null);
  const selected=selectedId ? growth.nodes[selectedId] : null;
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'end'});},[messages.length]);
  function submit(){if(!input.trim())return;send(input.trim());setInput('');}
  return <aside className="conversation-panel" aria-label="与 AI 一起思考"><header className="conversation-header"><div className="ai-symbol"><Sparkles size={21}/></div><div><h2>与 AI 一起思考</h2><p>基于当前空间 · {growth.nodes[spaceId].title}</p></div><span className="local-label">MOCK</span></header><div className="conversation-history"><div className="conversation-date"><span/>今天 · 9 月 16 日<span/></div>{messages.map(m=>{const p=proposals.find(p=>p.id===m.proposalId);const change=p?.actions.find(a=>a.type==='UPDATE_TIME');return <article className={`message ${m.role}`} key={m.id}><div className="message-byline">{m.role==='assistant'?<><Sparkles size={14}/><strong>知途</strong><span>与你一起</span></>:<><span className="user-dot">我</span><strong>我</strong></>}</div><div className="message-text">{m.text}</div>{p&&<div className="proposal"><span className="eyebrow">调整建议</span><strong>{p ? growth.nodes[p.nodeId]?.title : "时间调整"}</strong><p>{change ? `${change.startDate} — ${change.endDate}` : "更新计划安排"}</p>{p.status==='pending'?<div><button onClick={()=>{previewProposal(p.id);router.replace('/workbench?view=timeline');}}>查看影响<ArrowUpRight size={12}/></button><button className="primary-button" onClick={()=>accept(p.id)}>接受调整</button></div>:<span className="proposal-status">{p.status==='accepted'?'✓ 已接受，所有视图已同步':'日期已更新，此建议已失效'}</span>}</div>}</article>;})}<form className="inline-question-card" onSubmit={e=>{e.preventDefault();submit();}}><span>此刻最想先弄清楚什么？</span><div><input aria-label="卡片内回答" placeholder="在这张卡片里回答，也可以在下方继续…" value={input} onChange={e=>setInput(e.target.value)}/><button aria-label="发送卡片回答" disabled={!input.trim()}><ArrowUp size={14}/></button></div></form><div ref={bottom}/></div>
    <div className="composer-area">{selected?<div className="context-chip"><span className="tiny-dot"/>正在讨论：{selected.title}<button aria-label="清除上下文" onClick={()=>select(null)}><X size={12}/></button></div>:<div className="context-hint"><span className="tiny-dot"/>选择画布中的节点，让讨论更聚焦</div>}{showContexts&&<div className="context-options">{['academic','research','experience','personal'].map(id=><button key={id} onClick={()=>{select(id);setShowContexts(false);}}>{growth.nodes[id].title}</button>)}</div>}<form className="composer" onSubmit={e=>{e.preventDefault();submit();}}><textarea aria-label="给 AI 的消息" placeholder={selected?`关于「${selected.title}」，告诉 AI 你的想法……`:'有什么想法？我们一起梳理……'} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit();}}}/><div className="composer-actions"><button type="button" className="icon-button" aria-label="添加讨论对象" onClick={()=>setShowContexts(!showContexts)}><Plus size={18}/></button><span><CornerDownLeft size={11}/>发送 · Shift + Enter 换行</span><button type="submit" aria-label="发送消息" className="send-button" disabled={!input.trim()}><ArrowUp size={18}/></button></div></form><p className="composer-footnote">一起思考，由你决定。<span>本地演示 · 不连接 AI</span></p></div>
  </aside>;
}
