'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUpRight, Check, Clock3, Pause, Play, Sparkles } from 'lucide-react';
import { useDemo } from '@/features/growth/provider';
import { DEMO_TODAY } from '@/mock/growth-state';
export function Today() {
  const {growth,apply,enterSpace,focus,setFocus}=useDemo();const router=useRouter();const [why,setWhy]=useState(false);
  const today=Object.values(growth.nodes).filter(n=>n.type==='task'&&n.scheduledDate===DEMO_TODAY);
  const main=today.find(n=>n.id==='attention')??today[0]; const remaining=today.filter(n=>n.id!==main?.id);
  const minutes=Math.floor(focus.seconds/60).toString().padStart(2,'0');const seconds=(focus.seconds%60).toString().padStart(2,'0');
  return <div className="editorial-page today-page"><header className="editorial-header"><span className="eyebrow">WEDNESDAY, SEPTEMBER 16</span><span className="page-date">9 月 16 日 · 星期三</span><h1>晚上好，<br/>继续向理想的自己前进。</h1><p>不必一次走很远。今天，把这一件事做好。</p></header><div className="today-columns"><section><div className="section-label"><span>今天最重要的事</span><span>01 / FOCUS</span></div>{main?<div className="focus-card"><div className="focus-category"><span className="tiny-dot"/>科研能力 · 基础学习</div><button className="focus-title" onClick={()=>{enterSpace(main.id);router.push('/workbench');}}>{main.title}<ArrowUpRight size={20}/></button><p>{main.description}</p><div className="focus-meta"><span><Clock3 size={14}/>预计 {Math.round((main.estimatedHours??1.5)*60)} min</span><span>一次只做一件事</span></div><div className="focus-bottom">{main.status==='completed'?<span className="completed-label"><Check size={17}/>今天的这一步，完成了。</span>:<><button className="primary-button" onClick={()=>setFocus(f=>({...f,nodeId:main.id,running:!f.running}))}>{focus.running?<Pause size={14}/>:<Play size={14}/>} {focus.running?'暂停专注':focus.seconds?'继续专注':'开始专注'}</button>{focus.seconds>0&&<><time className="focus-timer">{minutes}:{seconds}</time><button className="text-button" onClick={()=>{setFocus(f=>({...f,running:false}));apply({type:'UPDATE_STATUS',nodeId:main.id,status:'completed'});}}>完成学习<Check size={13}/></button></>}</>}</div></div>:<div className="empty-note">今天没有安排任务。去工作台为今天留一个小行动。</div>}<section className="up-next"><div className="section-label"><span>接下来</span><span>按自己的节奏</span></div>{remaining.map(n=><div className="today-task" key={n.id}><button className="task-check" aria-label={`完成${n.title}`} aria-pressed={n.status==='completed'} onClick={()=>apply({type:'UPDATE_STATUS',nodeId:n.id,status:n.status==='completed'?'pending':'completed'})}>{n.status==='completed'&&<Check size={13}/>}</button><button onClick={()=>{enterSpace(n.id);router.push('/workbench');}}>{n.title}<small>{n.description}</small></button><span>{n.estimatedHours?`${n.estimatedHours*60} min`:'今天'}</span></div>)}</section></section><aside className="today-aside"><Sparkles size={23}/><span className="eyebrow">来自知途的观察</span><h2>给今天，留一点余地。</h2><p>你今天课程安排比较满。<br/><br/>我把科研任务降低到了一个，优先保证课程任务和 Attention 学习。</p><button className="text-button" aria-expanded={why} onClick={()=>setWhy(!why)}>{why?'收起说明':'为什么这样安排？'}<ArrowUpRight size={13}/></button>{why&&<div className="insight-explanation">这是演示中的预设建议：长时间学习 Attention 已经需要较多精力，导师资料整理仅安排 30 分钟。减少切换，比塞满今天更重要。</div>}<div className="quiet-note">成长不只发生在<br/>完成任务的那一刻。</div></aside></div></div>;
}
