'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowUpRight, Check, FileText, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { useDemo } from '@/features/growth/provider';
import { assetSummaries, memories, profileEntries, reports } from '@/mock/life';
import type { AISettings } from '@/types/growth';
import { SpaceFiles } from '@/components/growth/SpaceFiles';
const toggles:{key:keyof Pick<AISettings,'proactive'|'adjust'|'critique'|'rest'>;label:string;note:string}[]=[{key:'proactive',label:'主动聊天',note:'在你可能需要帮助时开启对话'},{key:'adjust',label:'允许调整计划',note:'AI 提出建议，由你确认后生效'},{key:'critique',label:'允许批评',note:'直接指出问题，同时尊重你的感受'},{key:'rest',label:'提醒休息',note:'在连续投入时提醒你停一停'}];
export function ProfileDetail({slug}:{slug:string}) {
  const {growth,settings,setSettings,files,journals,enterSpace,focus}=useDemo();const router=useRouter();const [assetOwner,setAssetOwner]=useState<string|null>(null);
  const entry=profileEntries.find(e=>e.slug===slug);if(!entry)return <div className="editorial-page"><h1>没有找到这个页面</h1><Link href="/me">返回我的</Link></div>;
  const tasks=Object.values(growth.nodes).filter(n=>n.type==='task');const done=tasks.filter(n=>n.status==='completed').length;
  return <div className="editorial-page detail-page"><Link className="back-link" href="/me"><ArrowLeft size={14}/>我的</Link><header className="editorial-header"><span className="eyebrow">YOUR GROWTH, YOUR WAY</span><h1>{entry.title}</h1><p>{entry.detail}。</p></header>
    {slug==='settings'&&<div className="settings-content"><section><h2>AI 行为模式</h2><p>选择你喜欢的相处方式。</p><div className="mode-options">{['被动','陪伴','教练','严格'].map(mode=><button key={mode} aria-pressed={settings.mode===mode} className={settings.mode===mode?'active':''} onClick={()=>setSettings(s=>({...s,mode}))}>{settings.mode===mode&&<Check size={13}/>} {mode}</button>)}</div></section>{toggles.map(t=><div className="setting-row" key={t.key}><div><strong>{t.label}</strong><p>{t.note}</p></div><button role="switch" aria-label={t.label} aria-checked={settings[t.key]} className={`switch ${settings[t.key]?'on':''}`} onClick={()=>setSettings(s=>({...s,[t.key]:!s[t.key]}))}><span/></button></div>)}<section><h2>提醒频率</h2><div className="mode-options">{['低','中','高'].map(f=><button key={f} className={settings.frequency===f?'active':''} aria-pressed={settings.frequency===f} onClick={()=>setSettings(s=>({...s,frequency:f}))}>{f}</button>)}</div></section><p className="subtle-disclaimer">偏好在本次会话内保留。此 Demo 不发送真实提醒，也不自动修改计划。</p></div>}
    {slug==='memory'&&<><div className="memory-intro"><Sparkles size={24}/><h2>AI 目前认为</h2><p>这些理解是可以变化的，并不定义你。</p></div>{memories.map((text,i)=><div className="memory-row" key={text}><span>0{i+1}</span><p>{text}</p><small>演示记忆</small></div>)}<p className="subtle-disclaimer">当前为预设内容，不会自动读取你的设备或文件。</p></>}
    {slug==='assets'&&<><div className="asset-summary">{assetSummaries.map(a=><div key={a.title}><strong>{a.count}</strong><span>{a.title}</span></div>)}</div><p className="subtle-disclaimer">以上为成长档案示例。下方是本次体验中实际添加的空间文件。</p><div className="section-label"><span>空间中的资料</span><span>{files.filter(f=>growth.nodes[f.ownerId]).length} 个文件</span></div>{files.filter(f=>growth.nodes[f.ownerId]).length===0?<div className="empty-note">还没有文件。进入任意节点空间，添加你的第一份资料。<Link href="/workbench" className="text-button">打开工作台<ArrowUpRight size={13}/></Link></div>:files.filter(f=>growth.nodes[f.ownerId]).map(f=><button className="asset-row" key={f.id} onClick={()=>setAssetOwner(f.ownerId)}><FileText size={18}/><strong>{f.name}</strong><span>{growth.nodes[f.ownerId].title}</span><ArrowUpRight size={14}/></button>)}{assetOwner&&<section className="inline-files"><h2>{growth.nodes[assetOwner].title}</h2><SpaceFiles ownerId={assetOwner}/></section>}</>}
    {slug==='reports'&&<><div className="report-list">{reports.map(r=><Link key={r.id} href={`/me/reports/${r.id}`}><span className="eyebrow">{r.date}</span><h2>{r.title}<ArrowUpRight size={20}/></h2><p>{r.summary}</p></Link>)}</div><p className="subtle-disclaimer">报告为演示样例，尚未接入真实生成。</p></>}
    {slug==='archive'&&<div className="archive-timeline"><article><time>2026.09.16</time><h2>开始认真了解科研</h2><p>把不确定的方向，变成可探索的成长空间。</p><button className="text-button" onClick={()=>{enterSpace('research');router.push('/workbench');}}>进入科研空间<ArrowUpRight size={14}/></button></article><article><time>2026.09.14</time><h2>完成开学课程规划</h2><p>为核心课程留出稳定的时间。</p></article><article><time>2026.08.01</time><h2>和知途的第一次对话</h2><p>从「我想保研」开始，慢慢看清自己的方向。</p></article></div>}
    {slug==='profile'&&<><div className="long-portrait"><Sparkles size={23}/><h2>正在形成方向，也正在学习取舍。</h2><p>你对大模型和 AI 有真实的兴趣。面对新的方向，你会先认真了解，再寻找自己能够开始的位置。</p><p>同时，身边人的进度有时会让你焦虑。把计划缩小到一个具体行动，会比同时追赶很多目标更适合你。</p></div><div className="profile-facts"><div><span>当前优势</span><strong>学习意愿 · 自我觉察</strong></div><div><span>可以尝试</span><strong>减少并行目标 · 主动联系</strong></div></div><p className="subtle-disclaimer">这是 Demo 的预设画像，不是对你的真实评估。</p></>}
    {slug==='behavior'&&<><div className="behavior-stats"><div><span>本次计划完成</span><strong>{done}<small> / {tasks.length}</small></strong></div><div><span>专注时间</span><strong>{Math.floor(focus.seconds/60)}<small> min</small></strong></div><div><span>随笔记录</span><strong>{journals.length}<small> 篇</small></strong></div></div><section className="behavior-progress"><h2>行动正在积累</h2><div className="progress-track"><span style={{width:`${tasks.length?done/tasks.length*100:0}%`}}/></div><p>这里读取的是本次体验中的统一状态。完成任务、专注学习或写下随笔后，回来看看变化。</p></section></>}
  </div>;
}
export function ReportDetail({period}:{period:string}) {
  const report=reports.find(r=>r.id===period);return <div className="editorial-page detail-page"><Link className="back-link" href="/me/reports"><ArrowLeft size={14}/>成长报告</Link>{report?<><header className="editorial-header"><span className="eyebrow">{report.date}</span><h1>{report.title}</h1><p>{report.summary}</p></header><div className="report-body">{report.sections.map((s,i)=><section key={s}><span className="eyebrow">0{i+1} · {i===0?'看见变化':'下一步'}</span><p>{s}</p></section>)}</div><p className="subtle-disclaimer">演示报告 · 非实时生成</p></>:<h1>没有找到这份报告</h1>}</div>;
}
