'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowUp, ArrowUpRight, MessageCircle, Plus, Search, Sparkles } from 'lucide-react';
import { useDemo } from '@/features/growth/provider';
import { Dialog } from '@/components/ui/Dialog';
export function ConversationHub() {
  const {growth,messages,conversations,setConversations,sendHistory,enterSpace}=useDemo();const router=useRouter();
  const [active,setActive]=useState('admission');const [search,setSearch]=useState('');const [input,setInput]=useState('');const [creating,setCreating]=useState(false);const [title,setTitle]=useState('');const bottom=useRef<HTMLDivElement>(null);
  const all=[{id:'admission',title:'保研计划',linkedNodeIds:['goal','research','contact'],messages},...conversations];
  const current=all.find(c=>c.id===active)??all[0];const filtered=all.filter(c=>c.title.includes(search)||c.messages.some(m=>m.text.includes(search)));
  useEffect(()=>{bottom.current?.scrollIntoView({block:'end'});},[active,current.messages.length]);
  return <div className="conversation-hub"><aside className="hub-list"><header><span className="eyebrow">THINKING TOGETHER</span><h1>对话<button className="icon-button" aria-label="新建对话" onClick={()=>setCreating(true)}><Plus size={19}/></button></h1><label className="hub-search"><Search size={14}/><input aria-label="搜索历史对话" placeholder="搜索那些想法…" value={search} onChange={e=>setSearch(e.target.value)}/></label></header><div className="hub-list-items">{filtered.map((c,i)=><div key={c.id}>{(i===0||i===2||i===3)&&<span className="hub-day">{i===0?'今天':i===2?'昨天':'更早'}</span>}<button className={`hub-item ${active===c.id?'active':''}`} onClick={()=>setActive(c.id)}><MessageCircle size={15}/><div><strong>{c.title}</strong><p>{c.messages.at(-1)?.text.slice(0,32)||'开启一段新的思考'}</p></div></button></div>)}{!filtered.length&&<p className="empty-note">没有找到相关对话。</p>}</div><footer>有些答案，来自持续的对话。</footer></aside><section className="hub-thread"><header><div><span className="eyebrow">CONVERSATION</span><h2>{current.title}</h2></div><span className="local-label">本地演示</span></header><div className="hub-messages">{current.messages.length===0&&<div className="empty-note">从一个问题开始。不用急着有答案。</div>}{current.messages.map(m=><article className={`message ${m.role}`} key={m.id}><div className="message-byline">{m.role==='assistant'?<Sparkles size={15}/>:<span className="user-dot">我</span>}<strong>{m.role==='assistant'?'知途':'我'}</strong></div><div className="message-text">{m.text}</div></article>)}<div ref={bottom}/></div><div className="hub-linked"><span>关联内容</span>{current.linkedNodeIds.map(id=><button onClick={()=>{enterSpace(id);router.push('/workbench');}} key={id}>{growth.nodes[id]?.title}<ArrowUpRight size={12}/></button>)}</div><form className="hub-composer" onSubmit={e=>{e.preventDefault();if(input.trim()){sendHistory(active,input.trim());setInput('');}}}><textarea aria-label="继续历史对话" placeholder="继续思考，或提出新的问题……" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();if(input.trim()){sendHistory(active,input.trim());setInput('');}}}}/><button className="send-button" disabled={!input.trim()} aria-label="发送历史对话"><ArrowUp size={19}/></button></form></section>{creating&&<Dialog title="开启新的对话" onClose={()=>setCreating(false)}><form className="node-form" onSubmit={e=>{e.preventDefault();if(!title.trim())return;const id=crypto.randomUUID();setConversations(old=>[{id,title:title.trim(),linkedNodeIds:['goal'],messages:[]},...old]);setActive(id);setTitle('');setCreating(false);}}><label>这次想聊什么？<input autoFocus value={title} maxLength={60} onChange={e=>setTitle(e.target.value)} placeholder="给这段思考起个名字"/></label><button className="primary-button" disabled={!title.trim()}>开始对话</button></form></Dialog>}</div>;
}
