'use client';
import { useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ImagePlus, Link2, Tag, Sparkles, ArrowUpRight, X } from 'lucide-react';
import { useDemo } from '@/features/growth/provider';
import { FilePreview } from '@/components/growth/SpaceFiles';
import type { FileAsset } from '@/types/growth';
export function Journal() {
  const {growth,journals,publishJournal,files,enterSpace}=useDemo();const router=useRouter();
  const [content,setContent]=useState('');const [tag,setTag]=useState('');const [linked,setLinked]=useState('');const [images,setImages]=useState<File[]>([]);const input=useRef<HTMLInputElement>(null);const [tools,setTools]=useState(false);const [filter,setFilter]=useState('全部');const [preview,setPreview]=useState<FileAsset|null>(null);
  const visible=journals.filter(j=>filter==='全部'||j.tags?.includes(filter));
  return <div className="editorial-page journal-page"><header className="editorial-header"><span className="eyebrow">LITTLE THINGS, REAL GROWTH</span><h1>随笔</h1><p>记录一些东西。不需要整理，AI 会慢慢理解它们。</p></header><form className="journal-composer" onSubmit={e=>{e.preventDefault();if(!content.trim())return;publishJournal(content,tag.trim()?[tag.trim()]:[],linked?[linked]:[],images);setContent('');setImages([]);setTag('');setLinked('');}}><textarea aria-label="此刻的想法" placeholder="此刻的想法……" value={content} onChange={e=>setContent(e.target.value)} maxLength={10000}/>{images.length>0&&<div className="attachment-chips">{images.map((f,i)=><span key={i}>{f.name}<button type="button" aria-label={`移除图片 ${f.name}`} onClick={()=>setImages(old=>old.filter((_,index)=>index!==i))}><X size={12}/></button></span>)}</div>}{tools&&<div className="journal-options"><label>标签<input value={tag} placeholder="例如：科研" maxLength={16} onChange={e=>setTag(e.target.value)}/></label><label>关联计划<select aria-label="关联计划" value={linked} onChange={e=>setLinked(e.target.value)}><option value="">不关联</option>{Object.values(growth.nodes).map(n=><option value={n.id} key={n.id}>{n.title}</option>)}</select></label></div>}<div className="journal-composer-footer"><div><button type="button" onClick={()=>input.current?.click()}><ImagePlus size={15}/>图片</button><button type="button" onClick={()=>setTools(!tools)}><Tag size={15}/>标签</button><button type="button" onClick={()=>setTools(!tools)}><Link2 size={15}/>关联计划</button><input hidden ref={input} type="file" accept="image/*" multiple aria-label="随笔图片" onChange={e=>{setImages(old=>[...old,...Array.from(e.target.files??[]).filter(f=>f.type.startsWith('image/'))]);e.target.value='';}}/></div><button className="primary-button" disabled={!content.trim()}>发布</button></div></form><div className="journal-feed-header"><h2>最近</h2><div className="filter-row">{['全部','科研','思考','情绪'].map(t=><button key={t} className={filter===t?'active':''} onClick={()=>setFilter(t)}>{t}</button>)}</div></div>{visible.length===0&&<p className="empty-note">这个标签下还没有记录。</p>}{visible.map(j=><article className="journal-entry" key={j.id}><div className="journal-date"><span>SEP</span><strong>{j.date.slice(8)}</strong></div><div className="journal-body"><h2>{j.content.split('\n')[0]}</h2><p>{j.content.includes('\n')?j.content.slice(j.content.indexOf('\n')).trim():''}</p><div className="journal-tags">{j.tags?.map(t=><span key={t}># {t}</span>)}{j.linkedNodeIds.map(id=><button key={id} onClick={()=>{enterSpace(id);router.push('/workbench');}}>{growth.nodes[id]?.title}<ArrowUpRight size={11}/></button>)}</div>{files.filter(f=>f.ownerId===j.id).map(f=><button className="attachment-link" onClick={()=>setPreview(f)} key={f.id}><ImagePlus size={14}/>{f.name} · 查看</button>)}{j.insight&&<div className="journal-insight"><Sparkles size={15}/><span>从这篇记录中，我发现：<strong>{j.insight}</strong></span></div>}</div></article>)}{preview&&<FilePreview asset={preview} onClose={()=>setPreview(null)}/>}</div>;
}
