"""research cache and daily quota

Revision ID: 05a2fa981c8e
Revises: f8136f7d02e2
Create Date: 2026-10-02 14:07:20.502406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = '05a2fa981c8e'
down_revision: Union[str, Sequence[str], None] = 'f8136f7d02e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('fetching', 'success', 'failed', name='research_cache_status', native_enum=False, length=32), nullable=False),
    sa.Column('sources', backend.db.base.JsonDict(), nullable=False),
    sa.Column('lease_expires_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_cache')),
    sa.UniqueConstraint('cache_key', name='uq_research_cache_cache_key')
    )
    with op.batch_alter_table('research_cache', schema=None) as batch_op:
        batch_op.create_index('ix_research_cache_status_expires_at', ['status', 'expires_at'], unique=False)

    op.create_table('research_daily_quota',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('local_day', sa.Date(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_daily_quota')),
    sa.UniqueConstraint('provider', 'local_day', name='uq_research_daily_quota_provider_local_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_daily_quota')
    with op.batch_alter_table('research_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_research_cache_status_expires_at')

    op.drop_table('research_cache')
    # ### end Alembic commands ###
