"""add auth_sessions token_version

Revision ID: 2b4ac9e27af3
Revises: 3afc2912841f
Create Date: 2026-09-25 17:13:32.045567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = '2b4ac9e27af3'
down_revision: Union[str, Sequence[str], None] = '3afc2912841f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###
