"""node_analyses

Revision ID: 35b8423fa3d7
Revises: c4f8a1d6e9b3
Create Date: 2026-09-27 14:08:14.392410

AI 分析层的第一张表:一次分析记一行,附带它当时看到的输入。

## 这是一次**纯加法**迁移,但"纯加法"不等于"不用备份"

只 `create_table`,没有任何 `alter_column` / `drop` / `rename`:老数据的语义一点没变,
老代码在新库上照跑(它不知道这张表存在)。但**开发库里已经有真实数据**,所以升级前
仍然要取一份备份 —— 理由不是这次迁移危险,而是"数据库没有被改坏"这件事本身需要
一个可以回退的落点,而不是一句推理。

## downgrade **不是**无损回滚 —— 会删掉这一批生成的全部分析记录

`downgrade()` 里那一句 `drop_table('node_analyses')` 会**连同表里的行一起删掉**,
而这个上游没有任何地方能再把它们造出来:它们是模型当时说的话,不是从别处推导出来的。
所以回滚只能修好"表结构",修不回"那些分析"。

必须在回滚之前把要留的行导出(见下面那条导出命令)。**"反正能 downgrade 就没事"
在这里是错的** —— 这一批之后产出的每一条分析都只存在于这张表里。

## 升级与回滚步骤(开发库)

升级前:

    # 一致性备份。用 sqlite 自己的 backup API 而不是 cp:
    # 一边有连接在写、一边复制文件,拿到的是一个可能撕裂的库。
    python -c "import sqlite3; \
      src=sqlite3.connect('data/zhitu_dev.db'); \
      dst=sqlite3.connect('data/backup-zhitu_dev-before-node_analyses.db'); \
      src.backup(dst); dst.close(); src.close()"

    # 先在临时库上把整条迁移跑通,确认无误再动开发库。
    # **这一行是 bash 的写法**,PowerShell 里要写成两行:
    #   $env:DATABASE_URL = 'sqlite+aiosqlite:///./data/tmp-migrate-check.db'
    #   python -m alembic -c backend/alembic.ini upgrade head
    DATABASE_URL=sqlite+aiosqlite:///./data/tmp-migrate-check.db \
      python -m alembic -c backend/alembic.ini upgrade head

    # 升级开发库
    python -m alembic -c backend/alembic.ini upgrade head

回滚(**会删分析记录,先导出**):

    # 导出同样用 Python,不依赖机器上装没装 sqlite3 命令行。
    python -c "import sqlite3, csv; \
      con = sqlite3.connect('data/zhitu_dev.db'); \
      rows = con.execute('SELECT * FROM node_analyses').fetchall(); \
      con.close(); \
      w = csv.writer(open('data/node_analyses-before-downgrade.csv', 'w', newline='', encoding='utf-8')); \
      w.writerows(rows)"
    python -m alembic -c backend/alembic.ini downgrade -1

恢复:把上面那份 `backup-zhitu_dev-before-node_analyses.db` 换回 `data/zhitu_dev.db`
(先停掉开发后端),再重启。**换库会丢掉升级之后写入的一切** —— 备份是升级那一刻的
快照,不是"只回滚这张表"。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = '35b8423fa3d7'
down_revision: Union[str, Sequence[str], None] = 'c4f8a1d6e9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_analyses',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('scope_root_id', sa.Uuid(), nullable=True),
    sa.Column('focus_node_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('model_source', sa.Enum('openjiuwen', 'direct_llm', 'rule_fallback', 'unavailable', name='model_source', native_enum=False, length=32), nullable=True),
    sa.Column('input_snapshot', backend.db.base.JsonDict(), nullable=False),
    sa.Column('known', backend.db.base.JsonDict(), nullable=True),
    sa.Column('unknowns', backend.db.base.JsonDict(), nullable=True),
    sa.Column('evidence', backend.db.base.JsonDict(), nullable=True),
    sa.Column('assumptions', backend.db.base.JsonDict(), nullable=True),
    sa.Column('diagnosis', backend.db.base.JsonDict(), nullable=True),
    sa.Column('strategy_options', backend.db.base.JsonDict(), nullable=True),
    sa.Column('risks', backend.db.base.JsonDict(), nullable=True),
    sa.Column('confidence_note', sa.Text(), nullable=True),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_node_analyses_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['focus_node_id'], ['plan_nodes.id'], name=op.f('fk_node_analyses_focus_node_id_plan_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_node_analyses_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_root_id'], ['plan_nodes.id'], name=op.f('fk_node_analyses_scope_root_id_plan_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_node_analyses_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_node_analyses_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_analyses'))
    )
    with op.batch_alter_table('node_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_node_analyses_message_id', ['message_id'], unique=False)
        batch_op.create_index('ix_node_analyses_workspace_id_created_at', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('ix_node_analyses_workspace_id_focus_node_id_created_at', ['workspace_id', 'focus_node_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_node_analyses_workspace_id_focus_node_id_created_at')
        batch_op.drop_index('ix_node_analyses_workspace_id_created_at')
        batch_op.drop_index('ix_node_analyses_message_id')

    op.drop_table('node_analyses')
    # ### end Alembic commands ###
