"""goal reasoning idempotency and title lock

Revision ID: 37bb1f4aabe7
Revises: 662e52d10186
Create Date: 2026-10-02 16:58:38.442028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = '37bb1f4aabe7'
down_revision: Union[str, Sequence[str], None] = '662e52d10186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_reasoning_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_idempotency_key', sa.String(length=64), nullable=True))

    with op.batch_alter_table('reasoning_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_locked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reasoning_nodes', schema=None) as batch_op:
        batch_op.drop_column('title_locked')

    with op.batch_alter_table('goal_reasoning_sessions', schema=None) as batch_op:
        batch_op.drop_column('last_idempotency_key')

    # ### end Alembic commands ###
