"""initial schema

Revision ID: 3afc2912841f
Revises: 
Create Date: 2026-09-25 17:02:52.719325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = '3afc2912841f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('school', sa.String(length=120), nullable=True),
    sa.Column('major', sa.String(length=120), nullable=True),
    sa.Column('year', sa.String(length=32), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('target_goal', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('email = lower(trim(email))', name=op.f('ck_users_email_is_canonical')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('rotated_from_id', sa.Uuid(), nullable=True),
    sa.Column('rotated_to_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rotated_from_id'], ['auth_sessions.id'], name=op.f('fk_auth_sessions_rotated_from_id_auth_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rotated_to_id'], ['auth_sessions.id'], name=op.f('fk_auth_sessions_rotated_to_id_auth_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_auth_sessions_user_id_expires_at', ['user_id', 'expires_at'], unique=False)

    op.create_table('availability_exceptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('available_minutes', sa.Integer(), nullable=True),
    sa.Column('is_unavailable', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_minutes IS NULL OR available_minutes >= 0', name=op.f('ck_availability_exceptions_available_minutes_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_availability_exceptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_exceptions')),
    sa.UniqueConstraint('user_id', 'on_date', name='uq_availability_exceptions_user_id_on_date')
    )
    op.create_table('availability_rules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('rule', 'exception', 'user_block', name='availability_source', native_enum=False, length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_minute <= 1440', name=op.f('ck_availability_rules_end_minute_within_day')),
    sa.CheckConstraint('start_minute < end_minute', name=op.f('ck_availability_rules_start_before_end')),
    sa.CheckConstraint('start_minute >= 0', name=op.f('ck_availability_rules_start_minute_non_negative')),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name=op.f('ck_availability_rules_weekday_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_availability_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_rules'))
    )
    with op.batch_alter_table('availability_rules', schema=None) as batch_op:
        batch_op.create_index('ix_availability_rules_user_id_weekday', ['user_id', 'weekday'], unique=False)

    op.create_table('user_capacity_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weekly_total_minutes', sa.Integer(), nullable=False),
    sa.Column('safety_factor', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('daily_max_minutes', sa.Integer(), nullable=True),
    sa.Column('default_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('min_session_minutes', sa.Integer(), nullable=False),
    sa.Column('max_session_minutes', sa.Integer(), nullable=False),
    sa.Column('week_start_weekday', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('default_buffer_minutes >= 0', name=op.f('ck_user_capacity_profiles_default_buffer_minutes_non_negative')),
    sa.CheckConstraint('max_session_minutes >= min_session_minutes', name=op.f('ck_user_capacity_profiles_max_session_minutes_gte_min')),
    sa.CheckConstraint('min_session_minutes > 0', name=op.f('ck_user_capacity_profiles_min_session_minutes_positive')),
    sa.CheckConstraint('safety_factor >= 0.50 AND safety_factor <= 1.00', name=op.f('ck_user_capacity_profiles_safety_factor_range')),
    sa.CheckConstraint('weekly_total_minutes >= 0', name=op.f('ck_user_capacity_profiles_weekly_total_minutes_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_capacity_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_capacity_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_capacity_profiles_user_id'))
    )
    op.create_table('workspaces',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('intent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='workspace_status', native_enum=False, length=32), nullable=False),
    sa.Column('current_revision_version', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('archived_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workspaces_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index('ix_workspaces_owner_id_status', ['owner_id', 'status'], unique=False)

    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('primary', 'side', name='conversation_kind', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='conversation_status', native_enum=False, length=32), nullable=False),
    sa.Column('last_message_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_workspace_id_status', ['workspace_id', 'status'], unique=False)
        batch_op.create_index('uq_conversations_primary', ['workspace_id'], unique=True, postgresql_where=sa.text("kind = 'primary' AND status = 'active'"), sqlite_where=sa.text("kind = 'primary' AND status = 'active'"))

    op.create_table('domain_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('payload', backend.db.base.JsonDict(), nullable=True),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_domain_events_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_domain_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_events'))
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index('ix_domain_events_user_id_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_domain_events_workspace_id_kind', ['workspace_id', 'kind'], unique=False)

    op.create_table('planning_briefs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('current_level', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('weekly_available_minutes', sa.Integer(), nullable=True),
    sa.Column('constraints', backend.db.base.JsonDict(), nullable=True),
    sa.Column('risks', backend.db.base.JsonDict(), nullable=True),
    sa.Column('assumptions', backend.db.base.JsonDict(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'superseded', name='brief_status', native_enum=False, length=32), nullable=False),
    sa.Column('confirmed_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('weekly_available_minutes IS NULL OR weekly_available_minutes >= 0', name=op.f('ck_planning_briefs_weekly_available_minutes_non_negative')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_planning_briefs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_briefs')),
    sa.UniqueConstraint('workspace_id', 'version', name='uq_planning_briefs_workspace_id_version')
    )
    with op.batch_alter_table('planning_briefs', schema=None) as batch_op:
        batch_op.create_index('uq_planning_briefs_confirmed', ['workspace_id'], unique=True, postgresql_where=sa.text("status = 'confirmed'"), sqlite_where=sa.text("status = 'confirmed'"))

    op.create_table('proposals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'validated', 'pending_confirmation', 'applied', 'rejected', 'stale', 'failed', 'superseded', name='proposal_status', native_enum=False, length=32), nullable=False),
    sa.Column('base_revision_version', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.Enum('initial_plan', 'user_edit', 'execution_deviation', 'brief_change', 'deadline_change', 'manual_replan', name='proposal_trigger', native_enum=False, length=32), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('assumptions', backend.db.base.JsonDict(), nullable=True),
    sa.Column('change_summary', backend.db.base.JsonDict(), nullable=True),
    sa.Column('workload_check', backend.db.base.JsonDict(), nullable=True),
    sa.Column('conflict_check', backend.db.base.JsonDict(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('error_detail', sa.String(length=500), nullable=True),
    sa.Column('expires_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('decided_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_proposals_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_proposals_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_proposals_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals'))
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index('ix_proposals_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_proposals_workspace_id_status_created_at', ['workspace_id', 'status', 'created_at'], unique=False)

    op.create_table('plan_revisions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_revision_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', sa.Enum('initial_plan', 'user_edit', 'execution_deviation', 'brief_change', 'deadline_change', 'manual_replan', name='revision_trigger', native_enum=False, length=32), nullable=False),
    sa.Column('trigger_detail', sa.Text(), nullable=True),
    sa.Column('actor', sa.Enum('user', 'ai', 'scheduler', 'system', name='revision_actor', native_enum=False, length=32), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot', backend.db.base.JsonDict(), nullable=False),
    sa.Column('diff', backend.db.base.JsonDict(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['plan_revisions.id'], name=op.f('fk_plan_revisions_parent_revision_id_plan_revisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_plan_revisions_proposal_id_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_plan_revisions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_revisions')),
    sa.UniqueConstraint('workspace_id', 'version', name='uq_plan_revisions_workspace_id_version')
    )
    with op.batch_alter_table('plan_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_plan_revisions_workspace_id_version', ['workspace_id', 'version'], unique=False)

    op.create_table('proposal_decisions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('result', backend.db.base.JsonDict(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_proposal_decisions_proposal_id_proposals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_proposal_decisions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_decisions')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_proposal_decisions_user_id_idempotency_key')
    )
    with op.batch_alter_table('proposal_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_proposal_decisions_proposal_id', ['proposal_id'], unique=False)

    op.create_table('plan_nodes',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('node_type', sa.Enum('goal', 'capability', 'stage', 'task', 'milestone', name='node_type', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'doing', 'completed', 'archived', name='node_status', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='node_priority', native_enum=False, length=32), nullable=False),
    sa.Column('estimate_minutes', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('user', 'ai', name='node_origin', native_enum=False, length=32), nullable=False),
    sa.Column('plan_revision_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('depth >= 0', name=op.f('ck_plan_nodes_depth_non_negative')),
    sa.CheckConstraint('estimate_minutes IS NULL OR estimate_minutes > 0', name=op.f('ck_plan_nodes_estimate_minutes_positive')),
    sa.ForeignKeyConstraint(['parent_id'], ['plan_nodes.id'], name=op.f('fk_plan_nodes_parent_id_plan_nodes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_revision_id'], ['plan_revisions.id'], name=op.f('fk_plan_nodes_plan_revision_id_plan_revisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_plan_nodes_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_nodes'))
    )
    with op.batch_alter_table('plan_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_plan_nodes_deadline', ['deadline'], unique=False)
        batch_op.create_index('ix_plan_nodes_workspace_id_parent_id', ['workspace_id', 'parent_id'], unique=False)
        batch_op.create_index('ix_plan_nodes_workspace_id_status', ['workspace_id', 'status'], unique=False)

    op.create_table('dependencies',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('predecessor_id', sa.Uuid(), nullable=False),
    sa.Column('successor_id', sa.Uuid(), nullable=False),
    sa.Column('dep_type', sa.Enum('finish_to_start', name='dependency_type', native_enum=False, length=32), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('predecessor_id <> successor_id', name=op.f('ck_dependencies_no_self_dependency')),
    sa.ForeignKeyConstraint(['predecessor_id'], ['plan_nodes.id'], name=op.f('fk_dependencies_predecessor_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['plan_nodes.id'], name=op.f('fk_dependencies_successor_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_dependencies_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependencies')),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_dependencies_predecessor_id_successor_id')
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index('ix_dependencies_workspace_id_successor_id', ['workspace_id', 'successor_id'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('context_node_id', sa.Uuid(), nullable=True),
    sa.Column('model_source', sa.Enum('openjiuwen', 'direct_llm', 'rule_fallback', 'unavailable', name='model_source', native_enum=False, length=32), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.Enum('OPENJIUWEN_NOT_INSTALLED', 'NO_API_KEY', 'MODEL_TIMEOUT', 'MODEL_OUTPUT_INVALID', 'MODEL_AUTH_FAILED', 'MODEL_RATE_LIMITED', 'MODEL_UNAVAILABLE', 'CIRCUIT_OPEN', name='degraded_reason', native_enum=False, length=32), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('usage', backend.db.base.JsonDict(), nullable=True),
    sa.Column('client_message_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['context_node_id'], ['plan_nodes.id'], name=op.f('fk_messages_context_node_id_plan_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_messages_proposal_id_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_messages_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'seq', name='uq_messages_conversation_id_seq')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_workspace_id_created_at', ['workspace_id', 'created_at'], unique=False)
        batch_op.create_index('uq_messages_client_message_id', ['conversation_id', 'client_message_id'], unique=True, postgresql_where=sa.text('client_message_id IS NOT NULL'), sqlite_where=sa.text('client_message_id IS NOT NULL'))

    op.create_table('proposal_items',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('op', sa.Enum('create_node', 'update_node', 'delete_node', 'create_dependency', 'delete_dependency', 'schedule_sessions', 'unschedule_sessions', 'move_session', 'lock_session', 'update_brief', 'update_capacity', name='proposal_op', native_enum=False, length=32), nullable=False),
    sa.Column('local_id', sa.String(length=32), nullable=True),
    sa.Column('target_node_id', sa.Uuid(), nullable=True),
    sa.Column('payload', backend.db.base.JsonDict(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], name=op.f('fk_proposal_items_proposal_id_proposals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['plan_nodes.id'], name=op.f('fk_proposal_items_target_node_id_plan_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposal_items')),
    sa.UniqueConstraint('proposal_id', 'ordinal', name='uq_proposal_items_proposal_id_ordinal')
    )
    op.create_table('scheduled_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('plan_revision_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=True),
    sa.Column('end_minute', sa.Integer(), nullable=True),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'done', 'skipped', 'moved', 'canceled', name='scheduled_session_status', native_enum=False, length=32), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('lock_reason', sa.String(length=200), nullable=True),
    sa.Column('origin', sa.Enum('scheduler', 'user', 'ai', name='scheduled_session_origin', native_enum=False, length=32), nullable=False),
    sa.Column('moved_to_session_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_minutes IS NULL OR actual_minutes >= 0', name=op.f('ck_scheduled_sessions_actual_minutes_non_negative')),
    sa.CheckConstraint('buffer_minutes >= 0', name=op.f('ck_scheduled_sessions_buffer_minutes_non_negative')),
    sa.CheckConstraint('end_minute IS NULL OR (end_minute > 0 AND end_minute <= 1440)', name=op.f('ck_scheduled_sessions_end_minute_within_day')),
    sa.CheckConstraint('planned_minutes > 0', name=op.f('ck_scheduled_sessions_planned_minutes_positive')),
    sa.CheckConstraint('start_minute IS NULL OR (start_minute >= 0 AND start_minute < 1440)', name=op.f('ck_scheduled_sessions_start_minute_within_day')),
    sa.CheckConstraint('start_minute IS NULL OR end_minute IS NULL OR start_minute < end_minute', name=op.f('ck_scheduled_sessions_start_before_end')),
    sa.ForeignKeyConstraint(['moved_to_session_id'], ['scheduled_sessions.id'], name=op.f('fk_scheduled_sessions_moved_to_session_id_scheduled_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['plan_nodes.id'], name=op.f('fk_scheduled_sessions_node_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_revision_id'], ['plan_revisions.id'], name=op.f('fk_scheduled_sessions_plan_revision_id_plan_revisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scheduled_sessions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_scheduled_sessions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_sessions'))
    )
    with op.batch_alter_table('scheduled_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_scheduled_sessions_node_id', ['node_id'], unique=False)
        batch_op.create_index('ix_scheduled_sessions_user_id_scheduled_date_status', ['user_id', 'scheduled_date', 'status'], unique=False)
        batch_op.create_index('ix_scheduled_sessions_workspace_id_scheduled_date', ['workspace_id', 'scheduled_date'], unique=False)
        batch_op.create_index('uq_scheduled_sessions_slot', ['node_id', 'scheduled_date', 'seq'], unique=True, postgresql_where=sa.text("status NOT IN ('canceled', 'moved')"), sqlite_where=sa.text("status NOT IN ('canceled', 'moved')"))

    op.create_table('execution_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('completion_ratio', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('result', sa.Enum('completed', 'partial', 'skipped', 'failed', name='execution_result', native_enum=False, length=32), nullable=False),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('actual_minutes IS NULL OR actual_minutes >= 0', name=op.f('ck_execution_records_actual_minutes_non_negative')),
    sa.CheckConstraint('completion_ratio IS NULL OR (completion_ratio >= 0 AND completion_ratio <= 1)', name=op.f('ck_execution_records_completion_ratio_range')),
    sa.ForeignKeyConstraint(['node_id'], ['plan_nodes.id'], name=op.f('fk_execution_records_node_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['scheduled_sessions.id'], name=op.f('fk_execution_records_session_id_scheduled_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_execution_records_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_execution_records_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_records'))
    )
    with op.batch_alter_table('execution_records', schema=None) as batch_op:
        batch_op.create_index('ix_execution_records_node_id', ['node_id'], unique=False)
        batch_op.create_index('ix_execution_records_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_execution_records_user_id_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('uq_execution_records_idempotency', ['user_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'), sqlite_where=sa.text('idempotency_key IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_records', schema=None) as batch_op:
        batch_op.drop_index('uq_execution_records_idempotency', postgresql_where=sa.text('idempotency_key IS NOT NULL'), sqlite_where=sa.text('idempotency_key IS NOT NULL'))
        batch_op.drop_index('ix_execution_records_user_id_created_at')
        batch_op.drop_index('ix_execution_records_session_id')
        batch_op.drop_index('ix_execution_records_node_id')

    op.drop_table('execution_records')
    with op.batch_alter_table('scheduled_sessions', schema=None) as batch_op:
        batch_op.drop_index('uq_scheduled_sessions_slot', postgresql_where=sa.text("status NOT IN ('canceled', 'moved')"), sqlite_where=sa.text("status NOT IN ('canceled', 'moved')"))
        batch_op.drop_index('ix_scheduled_sessions_workspace_id_scheduled_date')
        batch_op.drop_index('ix_scheduled_sessions_user_id_scheduled_date_status')
        batch_op.drop_index('ix_scheduled_sessions_node_id')

    op.drop_table('scheduled_sessions')
    op.drop_table('proposal_items')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('uq_messages_client_message_id', postgresql_where=sa.text('client_message_id IS NOT NULL'), sqlite_where=sa.text('client_message_id IS NOT NULL'))
        batch_op.drop_index('ix_messages_workspace_id_created_at')

    op.drop_table('messages')
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index('ix_dependencies_workspace_id_successor_id')

    op.drop_table('dependencies')
    with op.batch_alter_table('plan_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_nodes_workspace_id_status')
        batch_op.drop_index('ix_plan_nodes_workspace_id_parent_id')
        batch_op.drop_index('ix_plan_nodes_deadline')

    op.drop_table('plan_nodes')
    with op.batch_alter_table('proposal_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_proposal_decisions_proposal_id')

    op.drop_table('proposal_decisions')
    with op.batch_alter_table('plan_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_revisions_workspace_id_version')

    op.drop_table('plan_revisions')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_proposals_workspace_id_status_created_at')
        batch_op.drop_index('ix_proposals_user_id')

    op.drop_table('proposals')
    with op.batch_alter_table('planning_briefs', schema=None) as batch_op:
        batch_op.drop_index('uq_planning_briefs_confirmed', postgresql_where=sa.text("status = 'confirmed'"), sqlite_where=sa.text("status = 'confirmed'"))

    op.drop_table('planning_briefs')
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index('ix_domain_events_workspace_id_kind')
        batch_op.drop_index('ix_domain_events_user_id_created_at')

    op.drop_table('domain_events')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('uq_conversations_primary', postgresql_where=sa.text("kind = 'primary' AND status = 'active'"), sqlite_where=sa.text("kind = 'primary' AND status = 'active'"))
        batch_op.drop_index('ix_conversations_workspace_id_status')

    op.drop_table('conversations')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index('ix_workspaces_owner_id_status')

    op.drop_table('workspaces')
    op.drop_table('user_capacity_profiles')
    with op.batch_alter_table('availability_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_availability_rules_user_id_weekday')

    op.drop_table('availability_rules')
    op.drop_table('availability_exceptions')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_sessions_user_id_expires_at')

    op.drop_table('auth_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
