"""goal reasoning map

Revision ID: 662e52d10186
Revises: f5052beabf5a
Create Date: 2026-10-02 16:53:13.241099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = '662e52d10186'
down_revision: Union[str, Sequence[str], None] = 'f5052beabf5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_reasoning_sessions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('root_plan_node_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.Enum('strategic_exploration', 'strategic_convergence', 'awaiting_strategy_confirmation', 'execution_planning', 'monitoring', name='reasoning_session_phase', native_enum=False, length=32), nullable=False),
    sa.Column('turn_action', sa.Enum('ask_user', 'analyze', 'expand', 'confirm', 'pause', 'complete', 'revisit', name='reasoning_turn_action', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('idle', 'running', 'ready', 'failed', name='reasoning_session_status', native_enum=False, length=32), nullable=False),
    sa.Column('focus_reasoning_node_id', sa.Uuid(), nullable=True),
    sa.Column('focus_reason', sa.Text(), nullable=True),
    sa.Column('map_version', sa.Integer(), nullable=False),
    sa.Column('input_version', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('explored_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_evaluated_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('strategy_proposal_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['root_plan_node_id'], ['plan_nodes.id'], name=op.f('fk_goal_reasoning_sessions_root_plan_node_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_proposal_id'], ['proposals.id'], name=op.f('fk_goal_reasoning_sessions_strategy_proposal_id_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_goal_reasoning_sessions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_reasoning_sessions')),
    sa.UniqueConstraint('workspace_id', name='uq_goal_reasoning_sessions_workspace_id')
    )
    op.create_table('reasoning_nodes',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('linked_plan_node_id', sa.Uuid(), nullable=True),
    sa.Column('handle', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('node_type', sa.Enum('dimension', 'question', 'risk', 'resource', 'route', 'assumption', name='reasoning_node_type', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('unexplored', 'exploring', 'resolved', 'paused', 'archived', name='reasoning_node_status', native_enum=False, length=32), nullable=False),
    sa.Column('next_action', sa.Enum('ask_user', 'analyze', 'expand', 'confirm', 'pause', 'complete', 'revisit', name='reasoning_node_next_action', native_enum=False, length=32), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('uncertainty', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('assumptions', backend.db.base.JsonDict(), nullable=False),
    sa.Column('evidence', backend.db.base.JsonDict(), nullable=False),
    sa.Column('source', sa.Enum('agent', 'user', 'research', name='reasoning_source', native_enum=False, length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_plan_node_id'], ['plan_nodes.id'], name=op.f('fk_reasoning_nodes_linked_plan_node_id_plan_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['reasoning_nodes.id'], name=op.f('fk_reasoning_nodes_parent_id_reasoning_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['goal_reasoning_sessions.id'], name=op.f('fk_reasoning_nodes_session_id_goal_reasoning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reasoning_nodes')),
    sa.UniqueConstraint('session_id', 'handle', name='uq_reasoning_nodes_session_id_handle')
    )
    with op.batch_alter_table('reasoning_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_reasoning_nodes_session_id_parent_id', ['session_id', 'parent_id'], unique=False)
        batch_op.create_index('ix_reasoning_nodes_session_id_status', ['session_id', 'status'], unique=False)

    op.create_table('reasoning_node_links',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('source_reasoning_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_reasoning_node_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.Enum('depends_on', 'influences', name='reasoning_link_type', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['goal_reasoning_sessions.id'], name=op.f('fk_reasoning_node_links_session_id_goal_reasoning_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_reasoning_node_id'], ['reasoning_nodes.id'], name=op.f('fk_reasoning_node_links_source_reasoning_node_id_reasoning_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_reasoning_node_id'], ['reasoning_nodes.id'], name=op.f('fk_reasoning_node_links_target_reasoning_node_id_reasoning_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reasoning_node_links')),
    sa.UniqueConstraint('session_id', 'source_reasoning_node_id', 'target_reasoning_node_id', 'link_type', name='uq_reasoning_node_links_session_id_source_target_type')
    )
    with op.batch_alter_table('reasoning_node_links', schema=None) as batch_op:
        batch_op.create_index('ix_reasoning_node_links_session_id', ['session_id'], unique=False)

    with op.batch_alter_table('agent_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning_node_id', sa.Uuid(), nullable=True))
        batch_op.create_index('ix_agent_questions_reasoning_node_id', ['reasoning_node_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_agent_questions_reasoning_node_id_reasoning_nodes'), 'reasoning_nodes', ['reasoning_node_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_agent_questions_reasoning_node_id_reasoning_nodes'), type_='foreignkey')
        batch_op.drop_index('ix_agent_questions_reasoning_node_id')
        batch_op.drop_column('reasoning_node_id')

    with op.batch_alter_table('reasoning_node_links', schema=None) as batch_op:
        batch_op.drop_index('ix_reasoning_node_links_session_id')

    op.drop_table('reasoning_node_links')
    with op.batch_alter_table('reasoning_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_reasoning_nodes_session_id_status')
        batch_op.drop_index('ix_reasoning_nodes_session_id_parent_id')

    op.drop_table('reasoning_nodes')
    op.drop_table('goal_reasoning_sessions')
    # ### end Alembic commands ###
