"""reminder states and execution content hash

Revision ID: 8b3ec72e4d24
Revises: fffa47d18272
Create Date: 2026-09-26 12:41:34.452967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = '8b3ec72e4d24'
down_revision: Union[str, Sequence[str], None] = 'fffa47d18272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reminder_key', sa.String(length=160), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('dismissed_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('snoozed_until', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminder_states_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_reminder_states_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_states')),
    sa.UniqueConstraint('user_id', 'reminder_key', name='uq_reminder_states_user_id_reminder_key')
    )
    with op.batch_alter_table('reminder_states', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_states_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('execution_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_records', schema=None) as batch_op:
        batch_op.drop_column('content_hash')

    with op.batch_alter_table('reminder_states', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_states_user_id')

    op.drop_table('reminder_states')
    # ### end Alembic commands ###
