"""plan node planning level

Revision ID: ab2745a76d7b
Revises: ad6a15a9f986
Create Date: 2026-10-01 23:45:40.235216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = 'ab2745a76d7b'
down_revision: Union[str, Sequence[str], None] = 'ad6a15a9f986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planning_level', sa.Enum('strategy', 'phase', 'month', 'week', 'day', name='planning_level', native_enum=False, length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_nodes', schema=None) as batch_op:
        batch_op.drop_column('planning_level')

    # ### end Alembic commands ###
