"""agent questions

Revision ID: ad6a15a9f986
Revises: 665fdb7d8d87
Create Date: 2026-10-01 23:22:22.252626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = 'ad6a15a9f986'
down_revision: Union[str, Sequence[str], None] = '665fdb7d8d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_questions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=True),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=False),
    sa.Column('response_mode', sa.Enum('single_select', 'multi_select', 'free_text', 'mixed', name='question_response_mode', native_enum=False, length=32), nullable=False),
    sa.Column('options', backend.db.base.JsonDict(), nullable=False),
    sa.Column('allow_custom_input', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'answered', 'investigating', 'resolved', 'archived', name='question_status', native_enum=False, length=32), nullable=False),
    sa.Column('answer', backend.db.base.JsonDict(), nullable=True),
    sa.Column('answer_client_id', sa.String(length=64), nullable=True),
    sa.Column('answered_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('events', backend.db.base.JsonDict(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('fk_agent_questions_source_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_node_id'], ['plan_nodes.id'], name=op.f('fk_agent_questions_source_node_id_plan_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_questions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_questions'))
    )
    with op.batch_alter_table('agent_questions', schema=None) as batch_op:
        batch_op.create_index('ix_agent_questions_source_message_id', ['source_message_id'], unique=False)
        batch_op.create_index('ix_agent_questions_source_node_id', ['source_node_id'], unique=False)
        batch_op.create_index('ix_agent_questions_workspace_id_status_created_at', ['workspace_id', 'status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_questions_workspace_id_status_created_at')
        batch_op.drop_index('ix_agent_questions_source_node_id')
        batch_op.drop_index('ix_agent_questions_source_message_id')

    op.drop_table('agent_questions')
    # ### end Alembic commands ###
