"""node relations and canvas layout

Revision ID: eab5fc18adde
Revises: 8b3ec72e4d24
Create Date: 2026-09-26 23:15:33.749814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = 'eab5fc18adde'
down_revision: Union[str, Sequence[str], None] = '8b3ec72e4d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_positions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['plan_nodes.id'], name=op.f('fk_node_positions_node_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_node_positions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_node_positions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_positions')),
    sa.UniqueConstraint('user_id', 'workspace_id', 'node_id', name='uq_node_positions_user_id_workspace_id_node_id')
    )
    with op.batch_alter_table('node_positions', schema=None) as batch_op:
        batch_op.create_index('ix_node_positions_workspace_id_node_id', ['workspace_id', 'node_id'], unique=False)

    op.create_table('node_relations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.Enum('related_to', 'influences', name='node_relation_type', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('origin', sa.Enum('user', 'ai', name='node_origin', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_node_id <> target_node_id', name=op.f('ck_node_relations_no_self_relation')),
    sa.ForeignKeyConstraint(['source_node_id'], ['plan_nodes.id'], name=op.f('fk_node_relations_source_node_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['plan_nodes.id'], name=op.f('fk_node_relations_target_node_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_node_relations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_relations')),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'relation_type', name='uq_node_relations_source_node_id_target_node_id_relation_type')
    )
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.create_index('ix_node_relations_source_node_id', ['source_node_id'], unique=False)
        batch_op.create_index('ix_node_relations_target_node_id', ['target_node_id'], unique=False)
        batch_op.create_index('ix_node_relations_workspace_id', ['workspace_id'], unique=False)

    op.create_table('scope_viewports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scope_node_id', sa.Uuid(), nullable=False),
    sa.Column('zoom', sa.Float(), nullable=False),
    sa.Column('pan_x', sa.Float(), nullable=False),
    sa.Column('pan_y', sa.Float(), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scope_node_id'], ['plan_nodes.id'], name=op.f('fk_scope_viewports_scope_node_id_plan_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scope_viewports_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_scope_viewports_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_viewports')),
    sa.UniqueConstraint('user_id', 'workspace_id', 'scope_node_id', name='uq_scope_viewports_user_id_workspace_id_scope_node_id')
    )
    with op.batch_alter_table('plan_nodes', schema=None) as batch_op:
        # server_default 不是省事,是**唯一能让两端都跑起来的写法**:SQLite 的
        # ADD COLUMN 不接受"NOT NULL 且无默认值"的列(不论表里有没有数据)。删掉它
        # 本地升级立刻报错,而 PostgreSQL 上照样通过 —— 又一个本地与线上的静默分叉。
        # 它必须和模型上的 `server_default` 同时存在,否则 DDL 对拍会失败。
        batch_op.add_column(sa.Column('content_version', sa.Integer(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_nodes', schema=None) as batch_op:
        batch_op.drop_column('content_version')

    op.drop_table('scope_viewports')
    with op.batch_alter_table('node_relations', schema=None) as batch_op:
        batch_op.drop_index('ix_node_relations_workspace_id')
        batch_op.drop_index('ix_node_relations_target_node_id')
        batch_op.drop_index('ix_node_relations_source_node_id')

    op.drop_table('node_relations')
    with op.batch_alter_table('node_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_node_positions_workspace_id_node_id')

    op.drop_table('node_positions')
    # ### end Alembic commands ###
