"""reasoning states and tool calls

Revision ID: f8136f7d02e2
Revises: ab2745a76d7b
Create Date: 2026-10-02 00:39:44.611807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = 'f8136f7d02e2'
down_revision: Union[str, Sequence[str], None] = 'ab2745a76d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasoning_states',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('context_node_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('uncertainty', sa.Integer(), nullable=False),
    sa.Column('facts_summary', backend.db.base.JsonDict(), nullable=False),
    sa.Column('assumptions', backend.db.base.JsonDict(), nullable=False),
    sa.Column('open_questions', backend.db.base.JsonDict(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Enum('read_tool', 'ask_user', 'synthesize', 'stop', name='reasoning_action', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('unexplored', 'exploring', 'blocked', 'resolved', 'abandoned', name='reasoning_status', native_enum=False, length=32), nullable=False),
    sa.Column('tool_calls_used', sa.Integer(), nullable=False),
    sa.Column('model_calls_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_node_id'], ['plan_nodes.id'], name=op.f('fk_reasoning_states_context_node_id_plan_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['reasoning_states.id'], name=op.f('fk_reasoning_states_parent_id_reasoning_states'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['agent_questions.id'], name=op.f('fk_reasoning_states_question_id_agent_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('fk_reasoning_states_source_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_reasoning_states_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reasoning_states'))
    )
    with op.batch_alter_table('reasoning_states', schema=None) as batch_op:
        batch_op.create_index('ix_reasoning_states_source_message_id', ['source_message_id'], unique=False)
        batch_op.create_index('ix_reasoning_states_workspace_id_status', ['workspace_id', 'status'], unique=False)

    op.create_table('tool_call_records',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('reasoning_state_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('sanitized_arguments', backend.db.base.JsonDict(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'error', 'rejected', name='tool_call_status', native_enum=False, length=32), nullable=False),
    sa.Column('result_summary', backend.db.base.JsonDict(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', backend.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['reasoning_state_id'], ['reasoning_states.id'], name=op.f('fk_tool_call_records_reasoning_state_id_reasoning_states'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tool_call_records_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_call_records')),
    sa.UniqueConstraint('reasoning_state_id', 'sequence', name='uq_tool_call_records_state_sequence')
    )
    with op.batch_alter_table('tool_call_records', schema=None) as batch_op:
        batch_op.create_index('ix_tool_call_records_workspace_id', ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_call_records', schema=None) as batch_op:
        batch_op.drop_index('ix_tool_call_records_workspace_id')

    op.drop_table('tool_call_records')
    with op.batch_alter_table('reasoning_states', schema=None) as batch_op:
        batch_op.drop_index('ix_reasoning_states_workspace_id_status')
        batch_op.drop_index('ix_reasoning_states_source_message_id')

    op.drop_table('reasoning_states')
    # ### end Alembic commands ###
