"""schedule_applications

Revision ID: fffa47d18272
Revises: 2b4ac9e27af3
Create Date: 2026-09-26 01:03:19.497020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (UtcDateTime, JsonDict, ...) live in backend.db.base. Alembic
# renders them as fully-qualified names, so this import must be present in every
# generated migration or upgrade() fails with NameError at run time.
import backend.db.base


# revision identifiers, used by Alembic.
revision: str = 'fffa47d18272'
down_revision: Union[str, Sequence[str], None] = '2b4ac9e27af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_applications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('schedule_version', sa.String(length=32), nullable=False),
    sa.Column('result', backend.db.base.JsonDict(), nullable=False),
    sa.Column('created_at', backend.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_schedule_applications_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_schedule_applications_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_applications')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_schedule_applications_user_id_idempotency_key')
    )
    with op.batch_alter_table('schedule_applications', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_applications_workspace_id', ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_applications_workspace_id')

    op.drop_table('schedule_applications')
    # ### end Alembic commands ###
